name: Pester

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the selected branches
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Pester Tests
    # The job will run on Windows Server 2019+
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Check-out your repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout the Git repository
      uses: actions/checkout@v2

    # Windows only comes with an outdated version of Pester, so we need to update it
    - name: Install the required PowerShell modules
      shell: powershell
      timeout-minutes: 5
      run: |
        Install-Module -Name Pester -Force

    - name: Run Pester tests
      working-directory: Scripts
      run: ./Invoke-IPHelperTests.ps1
      shell: powershell
      timeout-minutes: 5

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: TestResults
        path: TestResults/*